In [3]:
import numpy as np
# 创建三维数组
arr = np.zeros((3,3,3))
# 将数组转换为矩阵
mat = np.matrix(arr)

ValueError: shape too large to be a matrix.

# 所以需要注意的是：矩阵只能是二维的，而数组可以是多维的。

In [6]:
# 创建数组的方法
alist = [1,2,3,4]
arr = np.array(alist)

arr2 = np.zeros(5)

arr3 = np.arange(12)

arr4 = np.arange(4,12)

# 100 steps from 0 to 1
arr5 = np.linspace(0, 1, 100)

In [7]:
img = np.zeros((5,5))
print(img)

[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]


In [9]:
cube = np.zeros((4,4,4))
print(cube)

[[[ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]]

 [[ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]]

 [[ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]]

 [[ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]]]


### 数组进行转换：
#### reshape 函数和 shape函数
    


In [10]:
arr1d = np.arange(12)
print(arr1d)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [11]:
# 将arr1d转换为3X4的数组
arr2d = arr1d.reshape(3, 4)
print(arr2d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [12]:
# 将arr1d转换为3维的
arr3d = arr1d.reshape(2, 2, 3)
print(arr3d)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


### 索引与切片


In [13]:
alist = [[1,2], [3,4]]
print(alist[0][1])

2


In [14]:
arr = np.array(alist)
print(arr[0,1])
print(arr[:, 1])

2
[2 4]


### 读与写


In [15]:
f = open('somefile.txt', 'r')
alist = f.readlines()
f.close()

In [19]:
f = open('newtextfile.txt', 'w')
f.writelines(alist)
f.close()


而当读取的文件比较大的时候，打开文件很慢，可以用numpy.adarray。

In [ ]:
import numpy as np 
arr = np.loadtxt('somefile.txt')
np.savetxt('somefile.txt')
